### ISSUE TITLE
"JavaScript" in Skills section 

### ISSUE THREAD

**Issue by F-Baker** [samaronybarros/samaronybarros#1]
Issue | Solution
--------|------------
The first entry in the 'Skills' subsection is spelled incorrectly | correct "Javascrip" to "JavaScript"

**Comment by samaronybarros** [comment]
Thanks @F-Baker 

Already solved 🙂

**Comment by F-Baker** [comment]
Any time :P 
Thank you for your tutorials, I'm using your MERN tutorial repo for a scripting project right now.
Have a good evening.

**Comment by samaronybarros** [comment]
Good to know @F-Baker 

I hope that tutorial is being useful to you. I already wrote another article for Typescript development.

Feel free to take a look at it.

https://itnext.io/animal-tribes-how-to-create-your-first-full-stack-typescript-graphql-application-76786e5520ed
